worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name amirbaddour.com www.amirbaddour.com;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name amirbaddour.com www.amirbaddour.com;

        ssl_certificate /etc/letsencrypt/live/amirbaddour.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/amirbaddour.com/privkey.pem;

        location /app/ {
            proxy_pass http://frontend-container:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://healthcheck-container:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS" always;
            add_header Access-Control-Allow-Headers "Content-Type" always;

            if ($request_method = OPTIONS) {
                return 204;
            }
        }

        location = / {
            return 301 /app/;
        }
    }
}